// This file contains the complete 78-card Tarot deck data.

const tarotDeck = [
    // Major Arcana (ไพ่ชุดใหญ่)
    { id: 0, name: 'The Fool', meaning_up: 'การเริ่มต้น, อิสระ, ความไร้เดียงสา, การผจญภัย', meaning_rev: 'ความประมาท, การตัดสินใจโง่เขลา, ความเสี่ยงที่ไม่จำเป็น', image: 'images/card_0.jpg' },
    { id: 1, name: 'The Magician', meaning_up: 'พลังสร้างสรรค์, ความสามารถ, การลงมือทำ, ทักษะ', meaning_rev: 'การหลอกลวง, การใช้พรสวรรค์ในทางที่ผิด, ขาดความมั่นใจ', image: 'images/card_1.jpg' },
    { id: 2, name: 'The High Priestess', meaning_up: 'สัญชาตญาณ, ความลับ, จิตใต้สำนึก, ปัญญา', meaning_rev: 'ความไม่แน่นอน, ความลับถูกเปิดเผย, ขาดการรับฟังเสียงภายใน', image: 'images/card_2.jpg' },
    { id: 3, name: 'The Empress', meaning_up: 'ความอุดมสมบูรณ์, การดูแล, ความเป็นแม่, ความงาม', meaning_rev: 'การพึ่งพาผู้อื่น, การขาดความคิดสร้างสรรค์, ความไม่มั่นคง', image: 'images/card_3.jpg' },
    { id: 4, name: 'The Emperor', meaning_up: 'อำนาจ, ความเป็นผู้นำ, โครงสร้าง, ความมั่นคง', meaning_rev: 'การใช้อำนาจในทางที่ผิด, ความเข้มงวดเกินไป, การควบคุม', image: 'images/card_4.jpg' },
    { id: 5, name: 'The Hierophant', meaning_up: 'ประเพณี, ความเชื่อ, การเรียนรู้, สถาบัน', meaning_rev: 'การท้าทายกฎเกณฑ์, ความคิดนอกกรอบ, การแหกคอก', image: 'images/card_5.jpg' },
    { id: 6, name: 'The Lovers', meaning_up: 'ความรัก, ความสัมพันธ์, การตัดสินใจ, ความปรองดอง', meaning_rev: 'ความขัดแย้ง, การตัดสินใจที่ผิดพลาด, ความไม่ลงรอยกัน', image: 'images/card_6.jpg' },
    { id: 7, name: 'The Chariot', meaning_up: 'ความมุ่งมั่น, การควบคุม, ชัยชนะ, ความก้าวหน้า', meaning_rev: 'การขาดทิศทาง, การยอมแพ้, การสูญเสียการควบคุม', image: 'images/card_7.jpg' },
    { id: 8, name: 'Strength', meaning_up: 'ความกล้าหาญ, ความอดทน, พลังภายใน, ความเมตตา', meaning_rev: 'ความอ่อนแอ, ความกลัว, การขาดความเชื่อมั่นในตนเอง', image: 'images/card_8.jpg' },
    { id: 9, name: 'The Hermit', meaning_up: 'การค้นหาตัวเอง, การแยกตัว, สติปัญญา, การนำทาง', meaning_rev: 'ความโดดเดี่ยว, การปลีกตัวออกจากสังคมมากเกินไป', image: 'images/card_9.jpg' },
    { id: 10, name: 'Wheel of Fortune', meaning_up: 'โชคชะตา, การเปลี่ยนแปลง, จุดเปลี่ยน, วัฏจักร', meaning_rev: 'โชคร้าย, การเปลี่ยนแปลงที่ไม่คาดฝัน, การต่อต้านการเปลี่ยนแปลง', image: 'images/card_10.jpg' },
    { id: 11, name: 'Justice', meaning_up: 'ความยุติธรรม, ความสมดุล, ความจริง, กฎหมาย', meaning_rev: 'ความไม่ยุติธรรม, ความไม่สมดุล, การโกหก', image: 'images/card_11.jpg' },
    { id: 12, name: 'The Hanged Man', meaning_up: 'การรอคอย, การเสียสละ, มุมมองใหม่, การปล่อยวาง', meaning_rev: 'การดื้อรั้น, การเสียสละโดยเปล่าประโยชน์, การหยุดนิ่ง', image: 'images/card_12.jpg' },
    { id: 13, name: 'Death', meaning_up: 'การสิ้นสุด, การเปลี่ยนแปลงครั้งใหญ่, การเปลี่ยนผ่าน', meaning_rev: 'การต่อต้านการเปลี่ยนแปลง, ความกลัวการเริ่มต้นใหม่', image: 'images/card_13.jpg' },
    { id: 14, name: 'Temperance', meaning_up: 'ความสมดุล, การประนีประนอม, ความอดทน, การผสมผสาน', meaning_rev: 'ความสุดโต่ง, ความไม่สมดุล, การขาดความอดทน', image: 'images/card_14.jpg' },
    { id: 15, name: 'The Devil', meaning_up: 'พันธนาการ, การเสพติด, ด้านมืด, วัตถุนิยม', meaning_rev: 'การปลดปล่อย, การหลุดพ้นจากพันธนาการ, อิสรภาพ', image: 'images/card_15.jpg' },
    { id: 16, name: 'The Tower', meaning_up: 'การเปลี่ยนแปลงกะทันหัน, การทำลาย, การเปิดเผยความจริง', meaning_rev: 'การหลีกเลี่ยงหายนะ, ความกลัวการเปลี่ยนแปลง', image: 'images/card_16.jpg' },
    { id: 17, name: 'The Star', meaning_up: 'ความหวัง, แรงบันดาลใจ, การเยียวยา, ความสงบสุข', meaning_rev: 'ความสิ้นหวัง, การขาดศรัทธา, ความท้อแท้', image: 'images/card_17.jpg' },
    { id: 18, name: 'The Moon', meaning_up: 'ภาพลวงตา, ความกลัว, ความไม่แน่นอน, สัญชาตญาณ', meaning_rev: 'ความสับสนคลี่คลาย, การเอาชนะความกลัว, ความชัดเจน', image: 'images/card_18.jpg' },
    { id: 19, name: 'The Sun', meaning_up: 'ความสำเร็จ, ความสุข, ความมีชีวิตชีวา, ความชัดเจน', meaning_rev: 'ความเศร้า, การมองโลกในแง่ร้าย, ความสำเร็จที่ล่าช้า', image: 'images/card_19.jpg' },
    { id: 20, name: 'Judgement', meaning_up: 'การตัดสิน, การฟื้นคืน, การตื่นรู้, การให้อภัย', meaning_rev: 'การวิจารณ์ตนเอง, การไม่ยอมรับอดีต, การตัดสินใจผิด', image: 'images/card_20.jpg' },
    { id: 21, name: 'The World', meaning_up: 'การบรรลุเป้าหมาย, ความสำเร็จ, การสิ้นสุดวัฏจักร, การเดินทาง', meaning_rev: 'ความไม่สมบูรณ์, การขาดเป้าหมาย, ความล่าช้า', image: 'images/card_21.jpg' },

    // Suit of Wands (ไพ่ชุดไม้เท้า)
    { id: 22, name: 'Ace of Wands', meaning_up: 'แรงบันดาลใจใหม่, โอกาส, การเติบโต, ศักยภาพ', meaning_rev: 'ความล่าช้า, การขาดแรงจูงใจ, โอกาสที่พลาดไป', image: 'images/card_22.jpg' },
    { id: 23, name: 'Two of Wands', meaning_up: 'การวางแผน, การตัดสินใจ, การมองไปข้างหน้า', meaning_rev: 'การขาดการวางแผน, ความกลัวในสิ่งที่ไม่รู้จัก', image: 'images/card_23.jpg' },
    { id: 24, name: 'Three of Wands', meaning_up: 'การขยายตัว, การรอคอยผลลัพธ์, การมองการณ์ไกล', meaning_rev: 'อุปสรรค, ความล่าช้า, การขาดวิสัยทัศน์', image: 'images/card_24.jpg' },
    { id: 25, name: 'Four of Wands', meaning_up: 'การเฉลิมฉลอง, ความสามัคคี, บ้าน, ความสุข', meaning_rev: 'ความไม่ลงรอยกันในบ้าน, การเปลี่ยนแปลงที่ไม่คาดคิด', image: 'images/card_25.jpg' },
    { id: 26, name: 'Five of Wands', meaning_up: 'การแข่งขัน, ความขัดแย้ง, การถกเถียง, ความท้าทาย', meaning_rev: 'การหลีกเลี่ยงความขัดแย้ง, การหาทางออกร่วมกัน', image: 'images/card_26.jpg' },
    { id: 27, name: 'Six of Wands', meaning_up: 'ชัยชนะ, การยอมรับ, ความสำเร็จ, เกียรติยศ', meaning_rev: 'ความพ่ายแพ้, การขาดการยอมรับ, ความอับอาย', image: 'images/card_27.jpg' },
    { id: 28, name: 'Seven of Wands', meaning_up: 'การปกป้อง, การยืนหยัด, ความท้าทาย, ความกล้าหาญ', meaning_rev: 'การยอมแพ้, การสูญเสียความมั่นใจ, การถูกครอบงำ', image: 'images/card_28.jpg' },
    { id: 29, name: 'Eight of Wands', meaning_up: 'ความรวดเร็ว, การเคลื่อนไหว, ข่าวสาร, การเดินทาง', meaning_rev: 'ความล่าช้า, อุปสรรค, การหยุดชะงัก', image: 'images/card_29.jpg' },
    { id: 30, name: 'Nine of Wands', meaning_up: 'ความอดทน, ความไม่ย่อท้อ, การป้องกัน, ความแข็งแกร่ง', meaning_rev: 'ความเหนื่อยล้า, การยอมแพ้, การป้องกันที่อ่อนแอ', image: 'images/card_30.jpg' },
    { id: 31, name: 'Ten of Wands', meaning_up: 'ภาระหนัก, ความรับผิดชอบ, ความเครียด, การทำงานหนัก', meaning_rev: 'การปลดปล่อยภาระ, การมอบหมายงาน, การล้มเหลว', image: 'images/card_31.jpg' },
    { id: 32, name: 'Page of Wands', meaning_up: 'ความกระตือรือร้น, การสำรวจ, ข่าวดี, ความคิดสร้างสรรค์', meaning_rev: 'ความลังเล, ข่าวร้าย, การขาดทิศทาง', image: 'images/card_32.jpg' },
    { id: 33, name: 'Knight of Wands', meaning_up: 'พลังงาน, ความหลงใหล, การผจญภัย, การลงมือทำ', meaning_rev: 'ความหุนหันพลันแล่น, ความใจร้อน, ความล่าช้า', image: 'images/card_33.jpg' },
    { id: 34, name: 'Queen of Wands', meaning_up: 'ความมั่นใจ, ความเป็นอิสระ, เสน่ห์, ความอบอุ่น', meaning_rev: 'ความอิจฉา, ความไม่มั่นคง, การขาดความมั่นใจ', image: 'images/card_34.jpg' },
    { id: 35, name: 'King of Wands', meaning_up: 'ความเป็นผู้นำ, วิสัยทัศน์, แรงบันดาลใจ, การควบคุม', meaning_rev: 'การใช้อำนาจในทางที่ผิด, ความใจร้อน, ความไม่เด็ดขาด', image: 'images/card_35.jpg' },

    // Suit of Cups (ไพ่ชุดถ้วย)
    { id: 36, name: 'Ace of Cups', meaning_up: 'ความรักครั้งใหม่, อารมณ์, ความสัมพันธ์, ความคิดสร้างสรรค์', meaning_rev: 'อารมณ์ที่ถูกปิดกั้น, ความรักที่ไม่สมหวัง, ความว่างเปล่า', image: 'images/card_36.jpg' },
    { id: 37, name: 'Two of Cups', meaning_up: 'ความร่วมมือ, ความผูกพัน, ความรัก, การดึงดูด', meaning_rev: 'ความแตกแยก, ความไม่ลงรอยกัน, การเลิกรา', image: 'images/card_37.jpg' },
    { id: 38, name: 'Three of Cups', meaning_up: 'มิตรภาพ, การเฉลิมฉลอง, การทำงานร่วมกัน, ความสุข', meaning_rev: 'การนินทา, การแตกกลุ่ม, ความโดดเดี่ยว', image: 'images/card_38.jpg' },
    { id: 39, name: 'Four of Cups', meaning_up: 'ความเบื่อหน่าย, การครุ่นคิด, การไม่พอใจ, การมองข้ามโอกาส', meaning_rev: 'การตื่นรู้, การยอมรับโอกาสใหม่ๆ, การมองโลกในแง่ดี', image: 'images/card_39.jpg' },
    { id: 40, name: 'Five of Cups', meaning_up: 'ความสูญเสีย, ความเสียใจ, ความผิดหวัง, การมองแง่ลบ', meaning_rev: 'การให้อภัย, การก้าวต่อไป, การมองเห็นด้านดี', image: 'images/card_40.jpg' },
    { id: 41, name: 'Six of Cups', meaning_up: 'ความทรงจำในอดีต, ความไร้เดียงสา, ความสุขในวัยเด็ก', meaning_rev: 'การยึดติดกับอดีต, การไม่ยอมโต, การมองข้ามปัจจุบัน', image: 'images/card_41.jpg' },
    { id: 42, name: 'Seven of Cups', meaning_up: 'ตัวเลือก, จินตนาการ, ภาพลวงตา, ความฝัน', meaning_rev: 'การตัดสินใจ, ความชัดเจน, การเผชิญหน้าความจริง', image: 'images/card_42.jpg' },
    { id: 43, name: 'Eight of Cups', meaning_up: 'การเดินจากไป, การค้นหาสิ่งที่ดีกว่า, การปล่อยวาง', meaning_rev: 'ความกลัวการเปลี่ยนแปลง, การยึดติด, การกลับไปที่เดิม', image: 'images/card_43.jpg' },
    { id: 44, name: 'Nine of Cups', meaning_up: 'ความสมหวัง, ความพึงพอใจ, ความสุข, พรที่สมปรารถนา', meaning_rev: 'ความไม่พอใจ, ความโลภ, ความฝันที่ไม่เป็นจริง', image: 'images/card_44.jpg' },
    { id: 45, name: 'Ten of Cups', meaning_up: 'ความสุขในครอบครัว, ความสมบูรณ์, ความรักที่ยั่งยืน', meaning_rev: 'ความขัดแย้งในครอบครัว, ความสัมพันธ์ที่แตกสลาย', image: 'images/card_45.jpg' },
    { id: 46, name: 'Page of Cups', meaning_up: 'ความคิดสร้างสรรค์, สัญชาตญาณ, ข่าวดีทางอารมณ์', meaning_rev: 'ความไม่มั่นคงทางอารมณ์, การปิดกั้นความคิดสร้างสรรค์', image: 'images/card_46.jpg' },
    { id: 47, name: 'Knight of Cups', meaning_up: 'ความโรแมนติก, เสน่ห์, การตามหาความฝัน, ข้อเสนอ', meaning_rev: 'ความเพ้อฝัน, อารมณ์ที่ไม่แน่นอน, การหลอกลวง', image: 'images/card_47.jpg' },
    { id: 48, name: 'Queen of Cups', meaning_up: 'ความเห็นอกเห็นใจ, สัญชาตญาณ, การดูแล, ความสงบ', meaning_rev: 'ความอ่อนไหวเกินไป, การควบคุมอารมณ์ไม่ได้', image: 'images/card_48.jpg' },
    { id: 49, name: 'King of Cups', meaning_up: 'การควบคุมอารมณ์, ความสมดุล, ความเมตตา, การทูต', meaning_rev: 'อารมณ์แปรปรวน, การหลอกลวง, การถูกชักจูง', image: 'images/card_49.jpg' },

    // Suit of Swords (ไพ่ชุดดาบ)
    { id: 50, name: 'Ace of Swords', meaning_up: 'ความคิดใหม่, ความชัดเจน, ความจริง, ชัยชนะทางปัญญา', meaning_rev: 'ความสับสน, การตัดสินใจผิด, การสื่อสารที่ผิดพลาด', image: 'images/card_50.jpg' },
    { id: 51, name: 'Two of Swords', meaning_up: 'ทางตัน, การตัดสินใจที่ยากลำบาก, การหลีกเลี่ยงความจริง', meaning_rev: 'ความลังเล, การเปิดใจรับความจริง, การตัดสินใจ', image: 'images/card_51.jpg' },
    { id: 52, name: 'Three of Swords', meaning_up: 'ความเจ็บปวด, ความเสียใจ, การพลัดพราก, ความจริงที่โหดร้าย', meaning_rev: 'การเยียวยา, การให้อภัย, การก้าวข้ามความเจ็บปวด', image: 'images/card_52.jpg' },
    { id: 53, name: 'Four of Swords', meaning_up: 'การพักผ่อน, การฟื้นฟู, การทำสมาธิ, การหยุดนิ่ง', meaning_rev: 'ความเหนื่อยล้า, การหยุดชะงัก, การไม่ยอมพัก', image: 'images/card_53.jpg' },
    { id: 54, name: 'Five of Swords', meaning_up: 'ความขัดแย้ง, การเอาชนะอย่างไม่ยุติธรรม, การสูญเสีย', meaning_rev: 'การประนีประนอม, การให้อภัย, การยุติความขัดแย้ง', image: 'images/card_54.jpg' },
    { id: 55, name: 'Six of Swords', meaning_up: 'การเปลี่ยนผ่าน, การเดินทาง, การก้าวข้ามอุปสรรค', meaning_rev: 'การติดอยู่กับที่, การเดินทางที่ล่าช้า, อุปสรรค', image: 'images/card_55.jpg' },
    { id: 56, name: 'Seven of Swords', meaning_up: 'การหลอกลวง, การทรยศ, การแอบทำอะไรลับหลัง', meaning_rev: 'การเปิดเผยความจริง, การยอมรับผิด, การเผชิญหน้า', image: 'images/card_56.jpg' },
    { id: 57, name: 'Eight of Swords', meaning_up: 'การถูกจำกัด, ความรู้สึกสิ้นหวัง, การมองไม่เห็นทางออก', meaning_rev: 'การปลดปล่อย, การมองเห็นทางออก, การเอาชนะอุปสรรค', image: 'images/card_57.jpg' },
    { id: 58, name: 'Nine of Swords', meaning_up: 'ความวิตกกังวล, ความกลัว, ฝันร้าย, ความเครียด', meaning_rev: 'การปล่อยวางความกลัว, การมองหาความช่วยเหลือ', image: 'images/card_58.jpg' },
    { id: 59, name: 'Ten of Swords', meaning_up: 'การสิ้นสุดที่เจ็บปวด, ความพ่ายแพ้, การถูกหักหลัง', meaning_rev: 'การฟื้นตัว, การเริ่มต้นใหม่หลังจากความล้มเหลว', image: 'images/card_59.jpg' },
    { id: 60, name: 'Page of Swords', meaning_up: 'ความอยากรู้อยากเห็น, การสื่อสาร, ข่าวสาร, พลังแห่งความคิด', meaning_rev: 'การนินทา, ข่าวลือ, การพูดโดยไม่คิด', image: 'images/card_60.jpg' },
    { id: 61, name: 'Knight of Swords', meaning_up: 'ความทะเยอทะยาน, การกระทำที่รวดเร็ว, การตัดสินใจเด็ดขาด', meaning_rev: 'ความหุนหันพลันแล่น, การกระทำโดยไม่คิด, ความก้าวร้าว', image: 'images/card_61.jpg' },
    { id: 62, name: 'Queen of Swords', meaning_up: 'ความฉลาด, ความเป็นอิสระ, ความชัดเจน, การตัดสินที่ยุติธรรม', meaning_rev: 'ความเย็นชา, การวิจารณ์ที่รุนแรง, ความขมขื่น', image: 'images/card_62.jpg' },
    { id: 63, name: 'King of Swords', meaning_up: 'อำนาจทางปัญญา, ความจริง, ความยุติธรรม, การตัดสินใจที่เด็ดขาด', meaning_rev: 'การใช้อำนาจในทางที่ผิด, ความโหดร้าย, การตัดสินที่ไม่ยุติธรรม', image: 'images/card_63.jpg' },

    // Suit of Pentacles (ไพ่ชุดเหรียญ)
    { id: 64, name: 'Ace of Pentacles', meaning_up: 'โอกาสทางการเงิน, ความมั่นคง, การเริ่มต้นโครงการใหม่', meaning_rev: 'โอกาสที่พลาดไป, การวางแผนทางการเงินที่ผิดพลาด', image: 'images/card_64.jpg' },
    { id: 65, name: 'Two of Pentacles', meaning_up: 'การปรับตัว, การจัดการ, การรักษาสมดุล, ความยืดหยุ่น', meaning_rev: 'การจัดการที่ผิดพลาด, ความไม่มั่นคง, การตัดสินใจไม่ถูก', image: 'images/card_65.jpg' },
    { id: 66, name: 'Three of Pentacles', meaning_up: 'การทำงานเป็นทีม, การร่วมมือ, ทักษะ, คุณภาพ', meaning_rev: 'การทำงานที่ไม่มีคุณภาพ, การขาดความร่วมมือ', image: 'images/card_66.jpg' },
    { id: 67, name: 'Four of Pentacles', meaning_up: 'การเก็บออม, ความมั่นคง, การควบคุม, การยึดติดกับวัตถุ', meaning_rev: 'ความโลภ, การสูญเสียทางการเงิน, การปล่อยวาง', image: 'images/card_67.jpg' },
    { id: 68, name: 'Five of Pentacles', meaning_up: 'ความยากจน, ความลำบาก, การถูกทอดทิ้ง, ความไม่มั่นคง', meaning_rev: 'การฟื้นตัว, การมองหาความช่วยเหลือ, การผ่านพ้นวิกฤต', image: 'images/card_68.jpg' },
    { id: 69, name: 'Six of Pentacles', meaning_up: 'การให้และการรับ, ความเมตตา, การแบ่งปัน, ความยุติธรรม', meaning_rev: 'หนี้สิน, การเอาเปรียบ, การให้โดยหวังผลตอบแทน', image: 'images/card_69.jpg' },
    { id: 70, name: 'Seven of Pentacles', meaning_up: 'การรอคอยผล, การลงทุนระยะยาว, ความอดทน, การประเมินผล', meaning_rev: 'การลงทุนที่สูญเปล่า, การขาดความอดทน, ความผิดหวัง', image: 'images/card_70.jpg' },
    { id: 71, name: 'Eight of Pentacles', meaning_up: 'การเรียนรู้ทักษะ, การทำงานหนัก, ความขยัน, การพัฒนาตนเอง', meaning_rev: 'การทำงานที่ไม่มีคุณภาพ, การขาดความมุ่งมั่น, ความเบื่อหน่าย', image: 'images/card_71.jpg' },
    { id: 72, name: 'Nine of Pentacles', meaning_up: 'ความสำเร็จทางการเงิน, ความเป็นอิสระ, ความสุขสบาย', meaning_rev: 'การพึ่งพาทางการเงิน, การสูญเสีย, การทำงานหนักเกินไป', image: 'images/card_72.jpg' },
    { id: 73, name: 'Ten of Pentacles', meaning_up: 'ความมั่งคั่ง, มรดก, ความมั่นคงของครอบครัว, การส่งต่อ', meaning_rev: 'ความขัดแย้งเรื่องมรดก, ความไม่มั่นคงทางการเงิน', image: 'images/card_73.jpg' },
    { id: 74, name: 'Page of Pentacles', meaning_up: 'โอกาสใหม่, การเรียนรู้, การวางแผน, ข่าวดีทางการเงิน', meaning_rev: 'การขาดความมุ่งมั่น, โอกาสที่พลาดไป, การไม่ลงมือทำ', image: 'images/card_74.jpg' },
    { id: 75, name: 'Knight of Pentacles', meaning_up: 'ความรับผิดชอบ, ความน่าเชื่อถือ, การทำงานหนัก, ความมุ่งมั่น', meaning_rev: 'ความขี้เกียจ, การขาดความรับผิดชอบ, ความดื้อรั้น', image: 'images/card_75.jpg' },
    { id: 76, name: 'Queen of Pentacles', meaning_up: 'การดูแลเอาใจใส่, ความมั่นคง, การจัดการบ้านและงาน', meaning_rev: 'ความไม่มั่นคง, การขาดการจัดการ, การยึดติดกับวัตถุ', image: 'images/card_76.jpg' },
    { id: 77, name: 'King of Pentacles', meaning_up: 'ความมั่งคั่ง, ความสำเร็จทางธุรกิจ, ความเป็นผู้นำ, ความมั่นคง', meaning_rev: 'การตัดสินใจทางการเงินที่ผิดพลาด, ความโลภ', image: 'images/card_77.jpg' }
];
window.tarotDeck = tarotDeck;